# Generated by Django 5.0.3 on 2024-05-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس منزل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_number',
            field=models.CharField(blank=True, max_length=11, verbose_name='تلفن ثابت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='کدملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sel_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='تلفن همراه'),
        ),
    ]
