# Generated by Django 5.0.3 on 2024-09-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emp_grade',
            field=models.CharField(blank=True, max_length=15, verbose_name='سمت شغلی'),
        ),
        migrations.AddField(
            model_name='user',
            name='emp_id',
            field=models.CharField(blank=True, max_length=15, verbose_name='کد کارمندی'),
        ),
        migrations.AddField(
            model_name='user',
            name='emp_unit',
            field=models.CharField(blank=True, choices=[('آموزشکده فنی بندر انزلی - شهید خدادادی', 'آموزشکده فنی بندر انزلی - شهید خدادادی'), ('آموزشکده فنی رستم آباد رودبار - سیدالشهداء', 'آموزشکده فنی رستم آباد رودبار - سیدالشهداء'), ('آموزشکده فنی رشت - شهید چمران', 'آموزشکده فنی رشت - شهید چمران')], max_length=50, verbose_name='محل کار'),
        ),
        migrations.AddField(
            model_name='user',
            name='pro_grade',
            field=models.CharField(blank=True, choices=[('کاردانی', 'کاردانی'), ('کارشناسی', 'کارشناسی')], max_length=15, verbose_name='مقطع درسی'),
        ),
        migrations.AddField(
            model_name='user',
            name='pro_id',
            field=models.CharField(blank=True, max_length=15, verbose_name='کد استادی'),
        ),
        migrations.AddField(
            model_name='user',
            name='pro_major',
            field=models.CharField(blank=True, choices=[('حسابداری', 'حسابداری'), ('کامپیوتر', 'کامپیوتر'), ('صنایع چوب', 'صنایع چوب'), ('عمران', 'عمران'), ('معماری', 'معماری'), ('برق', 'برق')], max_length=15, verbose_name='رشته درسی'),
        ),
        migrations.AddField(
            model_name='user',
            name='st_grade',
            field=models.CharField(blank=True, choices=[('کاردانی', 'کاردانی'), ('کارشناسی', 'کارشناسی')], max_length=15, verbose_name='مقطع تحصیلی'),
        ),
        migrations.AddField(
            model_name='user',
            name='st_id',
            field=models.CharField(blank=True, max_length=15, verbose_name='کد دانشجویی'),
        ),
        migrations.AddField(
            model_name='user',
            name='st_major',
            field=models.CharField(blank=True, choices=[('حسابداری', 'حسابداری'), ('کامپیوتر', 'کامپیوتر'), ('صنایع چوب', 'صنایع چوب'), ('عمران', 'عمران'), ('معماری', 'معماری'), ('برق', 'برق')], max_length=15, verbose_name='رشته تحصیلی'),
        ),
    ]
