# Generated by Django 5.0.3 on 2024-05-25 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_address_alter_user_home_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(verbose_name='آدرس منزل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='کدملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sel_number',
            field=models.CharField(max_length=15, verbose_name='تلفن همراه'),
        ),
    ]
