# Generated by Django 5.1.1 on 2024-09-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_emp_grade_user_emp_id_user_emp_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(blank=True, max_length=15, verbose_name='کد پرسنلی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_unit',
            field=models.CharField(blank=True, choices=[('آموزشکده فنی بندر انزلی - شهید خدادادی', 'آموزشکده فنی بندر انزلی - شهید خدادادی'), ('آموزشکده فنی رستم آباد رودبار - سیدالشهداء', 'آموزشکده فنی رستم آباد رودبار - سیدالشهداء'), ('آموزشکده فنی رشت - شهید چمران', 'آموزشکده فنی رشت - شهید چمران'), ('آموزشکده فنی پسران آسانه اشرفیه', 'آموزشکده فنی پسران آسانه اشرفیه'), ('آموزشکده فنی پسران لاهیجان-شهیدرجائی', 'آموزشکده فنی پسران لاهیجان-شهیدرجائی'), ('دانشکده فنی و حرفه ای صومعه سرا', 'دانشکده فنی و حرفه ای صومعه سرا'), ('آموزشکده فنی دختران رشت', 'آموزشکده فنی دختران رشت'), ('دانشگاه فنی و حرفه ای استان گیلان', 'دانشگاه فنی و حرفه ای استان گیلان')], max_length=50, verbose_name='محل کار'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='کدملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pro_grade',
            field=models.CharField(blank=True, choices=[('کاردانی', 'کاردانی'), ('کارشناسی', 'کارشناسی')], max_length=15, verbose_name='مقطع آموزشی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pro_major',
            field=models.CharField(blank=True, choices=[('حسابداری', 'حسابداری'), ('کامپیوتر', 'کامپیوتر'), ('صنایع چوب', 'صنایع چوب'), ('عمران', 'عمران'), ('معماری', 'معماری'), ('برق', 'برق')], max_length=15, verbose_name='رشته آموزشی'),
        ),
    ]
