# Generated by Django 5.0.3 on 2024-06-01 07:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_address_alter_user_birth_date_and_more'),
        ('books', '0014_books_keep_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(to='books.books', verbose_name='ذخیره شده ها'),
        ),
        migrations.AddField(
            model_name='user',
            name='reservation_limit',
            field=models.IntegerField(default=5, verbose_name='محدودیت رزرو'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس منزل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='کدملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sel_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='تلفن همراه'),
        ),
    ]
