# Generated by Django 5.1.1 on 2024-09-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_authors',
            field=models.BooleanField(default=False, verbose_name='ایجاد نویسندگان'),
        ),
        migrations.AddField(
            model_name='user',
            name='create_books',
            field=models.BooleanField(default=False, verbose_name='ایجاد کتاب ها'),
        ),
        migrations.AddField(
            model_name='user',
            name='create_categories',
            field=models.BooleanField(default=False, verbose_name='ایجاد دسته بندی ها'),
        ),
        migrations.AddField(
            model_name='user',
            name='create_reservations',
            field=models.BooleanField(default=False, verbose_name='ایجاد رزرو ها'),
        ),
        migrations.AddField(
            model_name='user',
            name='create_users',
            field=models.BooleanField(default=False, verbose_name='ایجاد کاربران'),
        ),
        migrations.AddField(
            model_name='user',
            name='delete_authors',
            field=models.BooleanField(default=False, verbose_name='حذف نویسندگان'),
        ),
        migrations.AddField(
            model_name='user',
            name='delete_books',
            field=models.BooleanField(default=False, verbose_name='حذف کتاب ها'),
        ),
        migrations.AddField(
            model_name='user',
            name='delete_categories',
            field=models.BooleanField(default=False, verbose_name='حذف دسته بندی ها'),
        ),
        migrations.AddField(
            model_name='user',
            name='delete_reservations',
            field=models.BooleanField(default=False, verbose_name='حذف رزرو ها'),
        ),
        migrations.AddField(
            model_name='user',
            name='delete_users',
            field=models.BooleanField(default=False, verbose_name='حذف کاربران'),
        ),
        migrations.AddField(
            model_name='user',
            name='update_authors',
            field=models.BooleanField(default=False, verbose_name='ویرایش نویسندگان'),
        ),
        migrations.AddField(
            model_name='user',
            name='update_books',
            field=models.BooleanField(default=False, verbose_name='ویرایش کتاب ها'),
        ),
        migrations.AddField(
            model_name='user',
            name='update_categories',
            field=models.BooleanField(default=False, verbose_name='ویرایش دسته بندی'),
        ),
        migrations.AddField(
            model_name='user',
            name='update_reservations',
            field=models.BooleanField(default=False, verbose_name='ویرایش رزرو ها'),
        ),
        migrations.AddField(
            model_name='user',
            name='update_users',
            field=models.BooleanField(default=False, verbose_name='ویرایش کاربران'),
        ),
        migrations.AddField(
            model_name='user',
            name='view_authors',
            field=models.BooleanField(default=False, verbose_name='مشاهده نویسندگان'),
        ),
        migrations.AddField(
            model_name='user',
            name='view_books',
            field=models.BooleanField(default=False, verbose_name='مشاهده کتاب ها'),
        ),
        migrations.AddField(
            model_name='user',
            name='view_categories',
            field=models.BooleanField(default=False, verbose_name='مشاهده دسته بندی ها'),
        ),
        migrations.AddField(
            model_name='user',
            name='view_reservations',
            field=models.BooleanField(default=False, verbose_name='مشاهده رزرو ها'),
        ),
        migrations.AddField(
            model_name='user',
            name='view_users',
            field=models.BooleanField(default=False, verbose_name='مشاهده کاربران'),
        ),
    ]
