# Generated by Django 5.1.1 on 2024-12-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_create_comments_user_delete_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='default-user.jpg', upload_to='uploads/profile/', verbose_name='تصویر'),
        ),
    ]
