# Generated by Django 5.1.1 on 2024-09-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_create_authors_user_create_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('دانشجو', 'دانشجو'), ('استاد', 'استاد'), ('کامند', 'کامند')], max_length=7, verbose_name='نقش'),
        ),
    ]
