# Generated by Django 5.0.3 on 2024-06-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_bookmarks_alter_user_picture'),
        ('books', '0018_rename_category_id_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='users', to='books.books', verbose_name='ذخیره شده ها'),
        ),
    ]
