# Generated by Django 5.1.1 on 2024-09-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pro_grade',
            field=models.CharField(blank=True, choices=[('کاردانی', 'کاردانی'), ('کارشناسی', 'کارشناسی'), ('کاردانی و کارشناسی', 'کاردانی و کارشناسی')], max_length=18, verbose_name='مقطع آموزشی'),
        ),
    ]
