# Generated by Django 5.1.1 on 2024-09-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_pro_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_grade',
            field=models.CharField(blank=True, max_length=255, verbose_name='سمت شغلی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('دانشجو', 'دانشجو'), ('استاد', 'استاد'), ('کارمند', 'کارمند')], max_length=7, verbose_name='نقش'),
        ),
    ]
