# Generated by Django 5.0.3 on 2024-07-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_birth_number_user_co_grade_user_co_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(verbose_name='آدرس منزل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_number',
            field=models.CharField(max_length=20, verbose_name='شماره شناسنامه'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fathers_name',
            field=models.CharField(max_length=50, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='کدملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('دانشجو', 'دانشجو'), ('استاد', 'استاد'), ('کامند', 'کامند')], max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='sel_number',
            field=models.CharField(max_length=15, verbose_name='تلفن همراه'),
        ),
    ]
