# Generated by Django 5.0.3 on 2024-07-13 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_user_co_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='co_grade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='co_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='co_unit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pro_grade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pro_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pro_major',
        ),
        migrations.RemoveField(
            model_name='user',
            name='st_grade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='st_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='st_major',
        ),
    ]
