# Generated by Django 5.0.3 on 2024-07-31 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
