# Generated by Django 5.0.3 on 2024-03-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام کتاب')),
                ('author', models.CharField(max_length=150, verbose_name='نویسنده')),
                ('publisher', models.CharField(max_length=255, verbose_name='ناشر')),
                ('number_of_pages', models.IntegerField(verbose_name='تعداد صفحات')),
                ('in_stock', models.IntegerField(default=1, verbose_name='موجودی')),
                ('pub_date', models.DateField(verbose_name='تاریخ انتشار')),
                ('edition', models.CharField(max_length=100, verbose_name='سری چاپ')),
                ('language', models.CharField(choices=[('خارجی', [('EN', 'انگلیسی'), ('FR', 'فرانسوی'), ('DE', 'آلمانی'), ('AR', 'عربی')]), ('داخلی', [('FA', 'فارسی'), ('KO', 'کردی'), ('TO', 'ترکی')])], max_length=25, verbose_name='زبان')),
                ('picture', models.ImageField(upload_to='uploads/books/', verbose_name='عکس کتاب')),
                ('for_adults', models.BooleanField(default=False, verbose_name='محدودیت سنی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('date_edited', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('slug', models.SlugField(max_length=255, verbose_name='لینک')),
            ],
        ),
    ]
