# Generated by Django 5.0.3 on 2024-03-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'کتاب', 'verbose_name_plural': 'کتاب ها'},
        ),
        migrations.RemoveField(
            model_name='books',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='books',
            name='pub_year',
            field=models.IntegerField(blank=True, default=0, verbose_name='سال انتشار'),
        ),
        migrations.AddField(
            model_name='books',
            name='translator',
            field=models.CharField(default='', max_length=150, verbose_name='مترجم'),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='books',
            name='edition',
            field=models.IntegerField(blank=True, verbose_name='سری چاپ'),
        ),
        migrations.AlterField(
            model_name='books',
            name='in_stock',
            field=models.IntegerField(blank=True, default=1, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='books',
            name='language',
            field=models.CharField(blank=True, choices=[('خارجی', [('EN', 'انگلیسی'), ('FR', 'فرانسوی'), ('DE', 'آلمانی'), ('AR', 'عربی')]), ('داخلی', [('FA', 'فارسی'), ('KO', 'کردی'), ('TO', 'ترکی')])], max_length=25, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='books',
            name='picture',
            field=models.ImageField(blank=True, upload_to='uploads/books/', verbose_name='عکس کتاب'),
        ),
        migrations.AlterField(
            model_name='books',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='لینک'),
        ),
    ]
