# Generated by Django 5.0.3 on 2024-03-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_books_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='لینک'),
        ),
    ]
