# Generated by Django 5.0.3 on 2024-03-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_books_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='language',
            field=models.CharField(blank=True, choices=[('خارجی', [('انگلیسی', 'انگلیسی'), ('فرانسوی', 'فرانسوی'), ('آلمانی', 'آلمانی'), ('عربی', 'عربی')]), ('داخلی', [('فارسی', 'فارسی'), ('کردی', 'کردی'), ('ترکی', 'ترکی')])], max_length=25, verbose_name='زبان'),
        ),
    ]
