# Generated by Django 5.0.3 on 2024-03-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_category_books_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.ManyToManyField(related_name='books', to='books.category'),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='books',
            name='edition',
            field=models.IntegerField(blank=True, null=True, verbose_name='سری چاپ'),
        ),
        migrations.AlterField(
            model_name='books',
            name='in_stock',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='books',
            name='language',
            field=models.CharField(blank=True, choices=[('خارجی', [('انگلیسی', 'انگلیسی'), ('فرانسوی', 'فرانسوی'), ('آلمانی', 'آلمانی'), ('عربی', 'عربی')]), ('داخلی', [('فارسی', 'فارسی'), ('کردی', 'کردی'), ('ترکی', 'ترکی')])], max_length=25, null=True, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='books',
            name='number_of_pages',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد صفحات'),
        ),
        migrations.AlterField(
            model_name='books',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/books/', verbose_name='عکس کتاب'),
        ),
        migrations.AlterField(
            model_name='books',
            name='pub_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='سال انتشار'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ناشر'),
        ),
        migrations.AlterField(
            model_name='books',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='books',
            name='translator',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='مترجم'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام دسته بندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='لینک'),
        ),
    ]
