# Generated by Django 5.0.3 on 2024-04-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_books_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='for_adults',
        ),
        migrations.AddField(
            model_name='books',
            name='age_category',
            field=models.CharField(blank=True, choices=[('کودک', 'کودک'), ('نوجوان', 'نوجوان'), ('بزرگسال', 'بزرگسال')], max_length=15, null=True, verbose_name='گروه سنی'),
        ),
    ]
