# Generated by Django 5.0.3 on 2024-04-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_books_for_adults_books_age_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='age_category',
            field=models.CharField(blank=True, choices=[('کودک', 'کودک'), ('نوجوان', 'نوجوان'), ('بزرگسال', 'بزرگسال')], default='نا معلوم', max_length=15, verbose_name='گروه سنی'),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='books',
            name='edition',
            field=models.IntegerField(blank=True, default=1, verbose_name='سری چاپ'),
        ),
        migrations.AlterField(
            model_name='books',
            name='in_stock',
            field=models.IntegerField(blank=True, default=1, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='books',
            name='language',
            field=models.CharField(blank=True, choices=[('خارجی', [('انگلیسی', 'انگلیسی'), ('فرانسوی', 'فرانسوی'), ('آلمانی', 'آلمانی'), ('عربی', 'عربی')]), ('داخلی', [('فارسی', 'فارسی'), ('کردی', 'کردی'), ('ترکی', 'ترکی')])], default='نا معلوم', max_length=25, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='books',
            name='number_of_pages',
            field=models.IntegerField(blank=True, default=0, verbose_name='تعداد صفحات'),
        ),
        migrations.AlterField(
            model_name='books',
            name='picture',
            field=models.ImageField(blank=True, upload_to='uploads/books/', verbose_name='عکس کتاب'),
        ),
        migrations.AlterField(
            model_name='books',
            name='pub_year',
            field=models.IntegerField(blank=True, default=0, verbose_name='سال انتشار'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.CharField(blank=True, default='نا معلوم', max_length=255, verbose_name='ناشر'),
        ),
        migrations.AlterField(
            model_name='books',
            name='translator',
            field=models.CharField(blank=True, default='نا معلوم', max_length=150, verbose_name='مترجم'),
        ),
    ]
