# Generated by Django 5.0.3 on 2024-06-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_books_author_alter_books_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='keep_duration',
            field=models.IntegerField(default=7, verbose_name='حداکثر میزان نگهداری'),
        ),
    ]
