# Generated by Django 5.0.3 on 2024-06-02 19:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_books_keep_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='توضیحات'),
        ),
    ]
