# Generated by Django 5.0.3 on 2024-06-08 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_books_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_id',
            new_name='id',
        ),
    ]
