# Generated by Django 5.0.3 on 2024-07-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_books_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='in_stock_user',
            field=models.IntegerField(blank=True, default=1, verbose_name='موجودی رزرو نشده'),
        ),
        migrations.AlterField(
            model_name='books',
            name='in_stock',
            field=models.IntegerField(blank=True, default=1, verbose_name='موجودی واقعی'),
        ),
    ]
