# Generated by Django 5.0.3 on 2024-07-03 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_books_in_stock_user_alter_books_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='keep_duration',
        ),
    ]
