# Generated by Django 5.0.3 on 2024-07-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_books_waiting_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='uploads/categories/', verbose_name='عکس دسته بندی'),
        ),
    ]
