# Generated by Django 5.1.1 on 2024-09-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_alter_books_publisher_alter_books_translator'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
