# Generated by Django 5.1.1 on 2024-09-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_books_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='test',
        ),
    ]
