# Generated by Django 5.1.1 on 2024-10-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('تایید شده', 'تایید شده'), ('درحال بررسی', 'درحال بررسی'), ('رد شده', 'رد شده')], default='درحال بررسی', max_length=11, verbose_name='وضعیت'),
        ),
    ]
