# Generated by Django 5.1.1 on 2024-12-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_remove_books_title_books_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='name',
            new_name='title',
        ),
    ]
