# Generated by Django 5.1.1 on 2024-12-08 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_alter_author_picture'),
        ('books', '0032_alter_comment_book_alter_comment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='books', to='author.author', verbose_name='نویسندگان'),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.category', verbose_name='دسته\u200cبندی\u200cها'),
        ),
        migrations.AlterField(
            model_name='books',
            name='waiting_users',
            field=models.ManyToManyField(blank=True, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='لیست انتظار'),
        ),
    ]
