# Generated by Django 5.1.1 on 2024-12-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_alter_author_picture'),
        ('books', '0033_alter_books_author_alter_books_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(related_name='books', to='author.author', verbose_name='نویسندگان'),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.ManyToManyField(related_name='books', to='books.category', verbose_name='دسته\u200cبندی\u200cها'),
        ),
    ]
