# Generated by Django 5.1.1 on 2024-12-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_alter_author_picture'),
        ('books', '0034_alter_books_author_alter_books_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='books', to='author.author', verbose_name='نویسندگان'),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.category', verbose_name='دسته\u200cبندی\u200cها'),
        ),
        migrations.AlterField(
            model_name='books',
            name='picture',
            field=models.ImageField(blank=True, default='default-book.jpg', upload_to='uploads/books/', verbose_name='عکس کتاب'),
        ),
    ]
