# Generated by Django 5.0.3 on 2024-04-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_picture_alter_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.ImageField(blank=True, upload_to='uploads/author', verbose_name='عکس'),
        ),
    ]
