# Generated by Django 5.0.3 on 2024-06-06 07:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_author_description_alter_author_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='توضیحات'),
        ),
    ]
