# Generated by Django 5.1.1 on 2024-10-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='parent_comment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
