# Generated by Django 5.0.3 on 2024-07-01 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='delivery_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 7, 1, 14, 3, 48, 207818, tzinfo=datetime.timezone.utc), verbose_name='تاریخ تحویل'),
        ),
    ]
