# Generated by Django 5.0.3 on 2024-07-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='delivery_date',
            field=models.DateField(blank=True, verbose_name='تاریخ تحویل'),
        ),
    ]
