# Generated by Django 5.0.3 on 2024-07-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='شماره رزرو'),
            preserve_default=False,
        ),
    ]
