# Generated by Django 5.0.3 on 2024-07-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('رزرو شده', 'رزرو شده'), ('لغو رزرو', 'لغو رزرو'), ('تحویل داده شده', 'تحویل داده شده'), ('بازگردانده نشده', 'بازگردانده نشده'), ('بازگردانده شده', 'بازگردانده شده')], default='رزرو شده', max_length=25, verbose_name='وضعیت رزرو'),
        ),
    ]
