# Generated by Django 5.1.1 on 2024-10-10 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_remove_books_test'),
        ('reservation', '0010_alter_reservation_book_alter_reservation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='extends', to='books.books', verbose_name='رزرو')),
            ],
            options={
                'verbose_name': 'تمدید رزرو',
                'verbose_name_plural': 'تمدید رزرو\u200cها',
                'ordering': ['-date_added'],
            },
        ),
    ]
