# Generated by Django 5.1.1 on 2024-10-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_reservation_extend_request_delete_extend'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ بازگشت کتاب'),
        ),
    ]
